INSERT INTO category (category_name) values ('Computer Build');
INSERT INTO category (category_name) values ('Car Collection');
INSERT INTO category (category_name) values ('Stamps');
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('keyboard', 1, 'gaming keyboard', 1, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('CPU', 1, 'gaming processor', 1, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('monitor', 1, 'gaming monitor', 1, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('mouse', 1, 'Corsair Mouse', 1, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('Ferrari', 1, 'La Ferrari', 2, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('Porsche', 1, '911 Turbo', 2, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('Lincoln Stamp', 10, 'Valuable', 3, 1);
INSERT INTO items (name, quantity, description, category_id, user_id) VALUES ('Washington Memorial Stamp', 100, 'Semi-valuable', 3, 1);